# Generated by Django 3.0.5 on 2020-06-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
